export const constants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    GETLOGGEDUSER_REQUEST: "GET_LOGGED_USER_REQUEST",
    GETLOGGEDUSER_SUCCESS: "GET_LOGGED_USER_SUCCESS",
    GETLOGGEDUSER_FAILURE: "GET_LOGGED_USER_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    ADDPRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADDPRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADDPRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

    GETPRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
    GETPRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GETPRODUCTS_FAILURE: "GET_PRODUCTS_FAILUIRE",

    SETISADDEDITEM_SUCCESS: "SET_IS_ADDED_ITEM_SUCCESS",

    // GETPRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    // GETPRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    // GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE"
}